Repository OlegShchavelev/ALTGnomeWiki, pull requests merged in 2024-06, with the labels that each got.

#394 nvidia.md - Правка мертвых ссылок
  docs/equipment/nvidia.md
Labels: bug

#396 Добавлено: YaSpeller + ReMark-Lint и проверка при PR
  .github/workflows/pr-check-remark.yml
  .github/workflows/pr-check-spell.yml
  .yaspellerrc
  docs/system/macbook.md
  docs/tips/macbook-pro-2010-wifi.md
  docs/using_gnome/add-fonts.md
  docs/using_gnome/keyboard-layouts.md
  docs/using_gnome/keyboard-shortcuts.md
  docs/using_gnome/launching-applications.md
  docs/using_gnome/look-background.md
  docs/using_gnome/look-resolution.md
  docs/using_gnome/scaling-the-screen.md
  docs/using_gnome/startup-applications.md
  docs/using_gnome/switching-apps.md
  docs/using_gnome/uniform-look.md
  package-lock.json
  package.json
Labels: enhancement

#403 Исправления заголовков для статей в соответствии с правилами и правки package.json
  .remarkignore
  docs/system/macbook.md
  docs/using_gnome/keyboard-layouts.md
  docs/using_gnome/net-antivirus.md
  package.json
Labels: documentation, enhancement

#408 Множественные исправления: Ошибки в статьях, дополнение словарей, правка команды CSpell и его шаблонов игнорирования блоков
  .cspell/anglicisms.dict
  .cspell/apps&companies.dict
  .cspell/people-names.dict
  .cspell/slang.dict
  .cspell/terms.dict
  .cspell/words.dict
  cspell.json
  docs/apps/pin-app.md
  docs/apps/port-proton.md
  docs/apps/speedtest.md
  docs/apps/steam.md
  docs/apps/telegram.md
  docs/apps/tuba.md
  docs/apps/zsh.md
  docs/build/build-packages.md
  docs/developers/podman.md
  docs/equipment/nvidia.md
  docs/main/quick-start.md
  docs/system/flatpak.md
  docs/system/macbook.md
  docs/system/neovim.md
  docs/using_gnome/add-empty-file-to-nautilus.md
  package.json
Labels: documentation, enhancement

#418 Заметки по использованию taskwarrior
  _data/navigations.ts
  docs/apps/taskwarrior.md
  docs/public/taskwarrior/task_burn_daily.png
  docs/public/taskwarrior/task_calendar.png
  docs/public/taskwarrior/task_calendar_fixed.png
  docs/public/taskwarrior/task_color.png
  docs/public/taskwarrior/task_ghistory.png
  docs/public/taskwarrior/task_undo.png
Labels: documentation, enhancement

#423 Небольшие правки: опечатка в команде установки и удаления пакета sysctl-conf-userns
  docs/system/flatpak.md
Labels: documentation, enhancement

#428 Добавлено: Установка и обновление программ | Librewolf
  _data/navigations.ts
  docs/apps/librewolf.md
Labels: documentation

#429 Обновлено: Статья про Ayugram и Librewolf всесто - на —
  docs/apps/ayugram-desktop.md
  docs/apps/librewolf.md
Labels: documentation, enhancement

#430 Обновлено: В браузеры добавлен Librewolf
  docs/main/wiki.md
Labels: documentation

#432 Обновлено: Сортировка участников
  .github/workflows/deploy.yml
  .github/workflows/pr-check-build.yml
  .gitignore
  .tools/gitlog.ts
  .vitepress/theme/components/AGWHomeTeam.vue
  .vitepress/theme/components/AGWHomeTeamButton.vue
  .vitepress/theme/components/AGWHomeTeamMembers.vue
  .vitepress/theme/components/AGWTeamLoader.vue
  .vitepress/theme/components/AGWTeamPage.vue
  .vitepress/theme/components/AGWTeamPageMembers.vue
  .vitepress/theme/composables/git/stats.js
  .vitepress/theme/composables/sorters.ts
  .vitepress/theme/index.mts
  README.md
  _data/gitlog-loader.data.ts
  _data/gitlog.ts
  _data/team.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement, appstream
